server:
  port: 8080

#  支付配置
pay:
# 微信支付配置
  weixinpay:
    # 公众号ID
    appid: appid
    # 公众帐号SECERT
    appsecret: appsecret
    # 商户ID
    mchid: mchid
    # 支付密钥
    apisign: apisign
    # 微信回调通知接口地址
    notifyurl: http://xxx.com/payment/wx/payNotify
#dev小程序支付配置
  mini:
  #小程序ID
    appid: appid
  #小程序密钥
    appsecret: appsecret
  #获取openid接口
    code2Session: https://api.weixin.qq.com/sns/jscode2session?appid={0}&secret={1}&js_code={2}&grant_type=authorization_code
  #统一下单接口
    unifiedorder: https://api.mch.weixin.qq.com/pay/unifiedorder
  #支付结果通知地址
    notifyUrl: https://wxz.hello.com/miniPay/notify